[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
standalone-linux-packager = ["dep:ar", "dep:cpio", "dep:md-5", "dep:rpm"]

[dependencies]
luxury-compiler.workspace = true
luxury-process.workspace = true
luxury-spec.workspace = true
luxury-windows-trust.workspace = true
serde_json.workspace = true
sha2.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
flate2.workspace = true
rustix.workspace = true
tar.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
luxury-macos-trust.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
ar = { version = "=0.9.0", optional = true }
cpio = { version = "=0.4.1", optional = true }
md-5 = { version = "=0.10.6", optional = true }
rpm = { version = "=0.16.1", default-features = false, features = ["gzip-compression"], optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[dev-dependencies]
tempfile.workspace = true
